/*
-- Query: SELECT * FROM bank_project.customer
LIMIT 0, 50000

-- Date: 2020-04-20 05:43
*/
INSERT INTO `` (`customer_id`,`customer_name_title`,`customer_first_name`,`customer_last_name`,`customer_gender`,`customer_job`,`customer_address`,`customer_country`,`customer_post_code`,`customer_email`,`customer_telephone`) VALUES (1,'Mr','john','wick','female','actor','65 moo 4 sub-district.dok khamtai district.dok khamtai','phayao','56120','ka_booooom@gmail.com','0871945284');
INSERT INTO `` (`customer_id`,`customer_name_title`,`customer_first_name`,`customer_last_name`,`customer_gender`,`customer_job`,`customer_address`,`customer_country`,`customer_post_code`,`customer_email`,`customer_telephone`) VALUES (2,'Miss','jill','supervalentine','male','actor','285/6 moo 1 soy 2 sub-district.pong district.pong','phayao','56140','super_valentine@gmail.com','0861947563');
INSERT INTO `` (`customer_id`,`customer_name_title`,`customer_first_name`,`customer_last_name`,`customer_gender`,`customer_job`,`customer_address`,`customer_country`,`customer_post_code`,`customer_email`,`customer_telephone`) VALUES (3,'Mr','phatut','otee','male','soldier','40/4 moo 4 sub-district.na prang district.pong','phayao','56140','phatut_otee@hotmail.com','0632854915');
INSERT INTO `` (`customer_id`,`customer_name_title`,`customer_first_name`,`customer_last_name`,`customer_gender`,`customer_job`,`customer_address`,`customer_country`,`customer_post_code`,`customer_email`,`customer_telephone`) VALUES (4,'Mrs','big','pom','female','teacher','69 moo 6 soy 9 sub-district.mae suk district.mae chai','phayao','56130','pompom_sleep@hotmail.com','0900999545');
INSERT INTO `` (`customer_id`,`customer_name_title`,`customer_first_name`,`customer_last_name`,`customer_gender`,`customer_job`,`customer_address`,`customer_country`,`customer_post_code`,`customer_email`,`customer_telephone`) VALUES (5,'Mr','yamamoto','teiki','male','engineering','123/4 moo 1 sub-district.ban lao district.mae chai','phayao','56130','godza_55@hotmail.com','0846299985');
INSERT INTO `` (`customer_id`,`customer_name_title`,`customer_first_name`,`customer_last_name`,`customer_gender`,`customer_job`,`customer_address`,`customer_country`,`customer_post_code`,`customer_email`,`customer_telephone`) VALUES (6,'Mr','bugs','bunny','male','chef','42 moo 9 sub-district.huai kaeo district.phu kamyao','phayao','56000','bugs_bunny@gmail.com','0632145695');
INSERT INTO `` (`customer_id`,`customer_name_title`,`customer_first_name`,`customer_last_name`,`customer_gender`,`customer_job`,`customer_address`,`customer_country`,`customer_post_code`,`customer_email`,`customer_telephone`) VALUES (7,'Mr','samsung','note','male','engineering','32/6 moo 5 soy 5 sub-district.dong chen district.phu kamyao','phayao','56000','note_9@hotmail.com','0806029423');
INSERT INTO `` (`customer_id`,`customer_name_title`,`customer_first_name`,`customer_last_name`,`customer_gender`,`customer_job`,`customer_address`,`customer_country`,`customer_post_code`,`customer_email`,`customer_telephone`) VALUES (8,'Miss','suzuki','koharu','female','chef','99/9 moo 9 soy 9 sub-district.huai khao Kam district.chun','phayao','56150','word_microsoft@hotmail.com','0895959451');
INSERT INTO `` (`customer_id`,`customer_name_title`,`customer_first_name`,`customer_last_name`,`customer_gender`,`customer_job`,`customer_address`,`customer_country`,`customer_post_code`,`customer_email`,`customer_telephone`) VALUES (9,'Mr','arthur','gssspotted','male','teacher','70/7 moo 1 sub-district.thung kluai district.phu sang','phayao','56110','gg_wp@hotmail.com','0994566590');
INSERT INTO `` (`customer_id`,`customer_name_title`,`customer_first_name`,`customer_last_name`,`customer_gender`,`customer_job`,`customer_address`,`customer_country`,`customer_post_code`,`customer_email`,`customer_telephone`) VALUES (10,'Dr','kamekame','haaa','male','doctor','54 moo 4 sub-district.chiang muan district.chiang muan','phayao','56160','goku_saiya@gamil.com','0945941139');
INSERT INTO `` (`customer_id`,`customer_name_title`,`customer_first_name`,`customer_last_name`,`customer_gender`,`customer_job`,`customer_address`,`customer_country`,`customer_post_code`,`customer_email`,`customer_telephone`) VALUES (11,'Mr','Luffy','D.Monkey','male','Butcher','113 moo 7  sub-district.NAKHON THAI','Phitsanulok','65120','PortgasD.Ace@gmail.com','0536749823');
INSERT INTO `` (`customer_id`,`customer_name_title`,`customer_first_name`,`customer_last_name`,`customer_gender`,`customer_job`,`customer_address`,`customer_country`,`customer_post_code`,`customer_email`,`customer_telephone`) VALUES (12,'Mr','zoro','Roronoa ','male','Guide','615 moo 4  sub-district.NOEN MAPRANG','Phitsanulok','65190','Roronoa.zoro@gmail.com','0844827894');
INSERT INTO `` (`customer_id`,`customer_name_title`,`customer_first_name`,`customer_last_name`,`customer_gender`,`customer_job`,`customer_address`,`customer_country`,`customer_post_code`,`customer_email`,`customer_telephone`) VALUES (13,'Mr','Chopper','Tony Tony','male','Doctor','8/8 moo 8  sub-district.Phai Lom','Phitsanulok','65110','Chopper.jun@hotmail.com','0945679290');
INSERT INTO `` (`customer_id`,`customer_name_title`,`customer_first_name`,`customer_last_name`,`customer_gender`,`customer_job`,`customer_address`,`customer_country`,`customer_post_code`,`customer_email`,`customer_telephone`) VALUES (14,'Miss','Robin','Nico','female','Archeologist','14 moo 5  sub-district.Khu Muang','Phitsanulok','65240','Robin.kun@gmail.com','0826727310');
INSERT INTO `` (`customer_id`,`customer_name_title`,`customer_first_name`,`customer_last_name`,`customer_gender`,`customer_job`,`customer_address`,`customer_country`,`customer_post_code`,`customer_email`,`customer_telephone`) VALUES (15,'Mr','Rayleigh','Silvers','male','Teacher','56/6 moo 9  sub-district.Ban Yang','Phitsanulok','65120','Gold_Roger@gmail.com','0530841910');
INSERT INTO `` (`customer_id`,`customer_name_title`,`customer_first_name`,`customer_last_name`,`customer_gender`,`customer_job`,`customer_address`,`customer_country`,`customer_post_code`,`customer_email`,`customer_telephone`) VALUES (16,'Mr','Newgate','Edward','male','Treasure hunter','13 moo 2  sub-district.Pak Thok','Phitsanulok','65000','Maruko_Phoenix@gmail.com','0844825607');
INSERT INTO `` (`customer_id`,`customer_name_title`,`customer_first_name`,`customer_last_name`,`customer_gender`,`customer_job`,`customer_address`,`customer_country`,`customer_post_code`,`customer_email`,`customer_telephone`) VALUES (17,'Mrs','Rinrin','Sharotto','female','actor','222 moo 6  sub-district.Wang Phikun','Phitsanulok','65130','Big_mom@gmail.com','0644821774');
INSERT INTO `` (`customer_id`,`customer_name_title`,`customer_first_name`,`customer_last_name`,`customer_gender`,`customer_job`,`customer_address`,`customer_country`,`customer_post_code`,`customer_email`,`customer_telephone`) VALUES (18,'Miss','Hancock','Boa','female','model','29 moo 4  sub-district.Bang Krathum','Phitsanulok','65110','D_Luffy@gmail.com','0899521923');
INSERT INTO `` (`customer_id`,`customer_name_title`,`customer_first_name`,`customer_last_name`,`customer_gender`,`customer_job`,`customer_address`,`customer_country`,`customer_post_code`,`customer_email`,`customer_telephone`) VALUES (19,'Mr','Doflamingo','Donquixote','male','Weaver','9/99 moo 5 sub-district.Phlai Chumphon','Phitsanulok','65000','joker.family@gmail.com','0537219872');
INSERT INTO `` (`customer_id`,`customer_name_title`,`customer_first_name`,`customer_last_name`,`customer_gender`,`customer_job`,`customer_address`,`customer_country`,`customer_post_code`,`customer_email`,`customer_telephone`) VALUES (20,'Mr','Law','Trafalgar','male','surgeon','79 moo 2  sub-district.Pa Daeng','Phitsanulok','65170','Papo_heart@gmail.com','0827219872');
INSERT INTO `` (`customer_id`,`customer_name_title`,`customer_first_name`,`customer_last_name`,`customer_gender`,`customer_job`,`customer_address`,`customer_country`,`customer_post_code`,`customer_email`,`customer_telephone`) VALUES (21,'Miss','ruby','theo','female','barber','75/9 moo 2 sub-district.dok khamtai district.dok khamtai','phayao','56120','gooogle@gmail.com','0888461475');
INSERT INTO `` (`customer_id`,`customer_name_title`,`customer_first_name`,`customer_last_name`,`customer_gender`,`customer_job`,`customer_address`,`customer_country`,`customer_post_code`,`customer_email`,`customer_telephone`) VALUES (22,'Miss','nitro','five','female','nurse','85/4 moo 1 sub-district.pong district.pong','phayao','56140','html_php@gmail.com','0995415846');
INSERT INTO `` (`customer_id`,`customer_name_title`,`customer_first_name`,`customer_last_name`,`customer_gender`,`customer_job`,`customer_address`,`customer_country`,`customer_post_code`,`customer_email`,`customer_telephone`) VALUES (23,'Mr','kamen','rider','male','policeman','55 moo 1 sub-district.na prang district.pong','phayao','56140','hen_shin@hotmail.com','066524789');
INSERT INTO `` (`customer_id`,`customer_name_title`,`customer_first_name`,`customer_last_name`,`customer_gender`,`customer_job`,`customer_address`,`customer_country`,`customer_post_code`,`customer_email`,`customer_telephone`) VALUES (24,'Mr','mouse','macnus','male','teacher','96/2 moo 4 soy 1 sub-district.mae suk district.mae chai','phayao','56130','power_point@hotmail.com','0913549528');
INSERT INTO `` (`customer_id`,`customer_name_title`,`customer_first_name`,`customer_last_name`,`customer_gender`,`customer_job`,`customer_address`,`customer_country`,`customer_post_code`,`customer_email`,`customer_telephone`) VALUES (25,'Miss','minami','neko','female','nurse','55 moo 2 sub-district.ban lao district.mae chai','phayao','56130','god_dog@hotmail.com','0638912254');
INSERT INTO `` (`customer_id`,`customer_name_title`,`customer_first_name`,`customer_last_name`,`customer_gender`,`customer_job`,`customer_address`,`customer_country`,`customer_post_code`,`customer_email`,`customer_telephone`) VALUES (26,'Mr','tom','jerry','male','chef','77 moo 1 sub-district.huai kaeo district.phu kamyao','phayao','56000','the_one@gmail.com','099741558');
INSERT INTO `` (`customer_id`,`customer_name_title`,`customer_first_name`,`customer_last_name`,`customer_gender`,`customer_job`,`customer_address`,`customer_country`,`customer_post_code`,`customer_email`,`customer_telephone`) VALUES (27,'Mr','acer','pro','male','engineering','26/9 moo 2 soy 4 sub-district.dong chen district.phu kamyao','phayao','56000','error_404@hotmail.com','0809095461');
INSERT INTO `` (`customer_id`,`customer_name_title`,`customer_first_name`,`customer_last_name`,`customer_gender`,`customer_job`,`customer_address`,`customer_country`,`customer_post_code`,`customer_email`,`customer_telephone`) VALUES (28,'Miss','yua','mikami','female','sport man','586/8 moo 1 soy 1 sub-district.huai khao Kam district.chun','phayao','56150','excel_microsoft@hotmail.com','0874652135');
INSERT INTO `` (`customer_id`,`customer_name_title`,`customer_first_name`,`customer_last_name`,`customer_gender`,`customer_job`,`customer_address`,`customer_country`,`customer_post_code`,`customer_email`,`customer_telephone`) VALUES (29,'Dr','heart','rocker','male','sport man','7/7 moo 5 sub-district.thung kluai district.phu sang','phayao','56110','game_filling@hotmail.com','0946525528');
INSERT INTO `` (`customer_id`,`customer_name_title`,`customer_first_name`,`customer_last_name`,`customer_gender`,`customer_job`,`customer_address`,`customer_country`,`customer_post_code`,`customer_email`,`customer_telephone`) VALUES (30,'Dr','christian','shop','male','doctor','64/8 moo 8 sub-district.chiang muan district.chiang muan','phayao','56160','playing_game@gamil.com','0803160520');
